version: "3.9"
services:
  xui:
    image: enwaiax/x-ui
    container_name: xui
    ports:
      - "54321:54321"
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    restart: always
    network_mode: host

  subconverter:
    image: stilleshan/sub
    container_name: sub
    volumes:
      - ./conf:/usr/share/nginx/html/conf
    restart: always
    networks:
      - v2r

  myurls:
    image: stilleshan/myurls:latest
    depends_on:
      - redis
    restart: always
    networks:
      - v2r

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    restart: always
    networks:
      - v2r


networks:
  v2r:
    driver: bridge