version: "3.3"
services:

  xui:
    image: enwaiax/x-ui
    container_name: xui
    ports:
      - "54321:54321"
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    restart: unless-stopped
    network_mode: host

  subconverter:
    image: stilleshan/sub
    container_name: sub
    ports:
      - 18080:80
    volumes:
      - ./conf:/usr/share/nginx/html/conf
    restart: always

  myurls:
    image: stilleshan/myurls:latest
    # container_name: myurls
    environment:
      - MYURLS_DOMAIN=s.ops.ci
      - MYURLS_TTL=365
    volumes:
      - ./data/myurls/logs:/app/logs    
    ports:
      - "8002:8002"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    # container_name: myurls-redis
    volumes:
      - ./data/redis:/data
    restart: always
