version: "3.9"
services:
  subconverter:
    image: stilleshan/sub
    container_name: sub
    ports:
      - 18080:80
    volumes:
      - ./conf:/usr/share/nginx/html/conf
    restart: always
    networks:
      - v2r

  myurls:
    image: stilleshan/myurls:latest
    # container_name: myurls
    environment:
      - MYURLS_DOMAIN=s.ops.ci
      - MYURLS_TTL=365
    volumes:
      - ./data/myurls/logs:/app/logs    
    ports:
      - "8002:8002"
    depends_on:
      - redis
    restart: always
    networks:
      - v2r

  redis:
    image: redis:latest
    # container_name: myurls-redis
    volumes:
      - ./data/redis:/data
    restart: always
    networks:
      - v2r
  xui:
    image: enwaiax/x-ui
    container_name: xui
    ports:
      - "54321:54321"
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    restart: always
    network_mode: host

networks:
  v2r:
    driver: bridge